### ISSUE TITLE
Logic in BaseConfigLoader for detecting bool conf values is incorrect

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#141]
If a config setting has a boolean value and is overridden in a config file, it will cause an exception on app startup:

```
Traceback (most recent call last):
  File "/Users/jharrington/code/ClusterRunner/main.py", line 274, in <module>
    main(sys.argv[1:])
  File "/Users/jharrington/code/ClusterRunner/main.py", line 259, in main
    _initialize_configuration(parsed_args.pop('subcommand'), parsed_args.pop('config_file'))
  File "/Users/jharrington/code/ClusterRunner/main.py", line 212, in _initialize_configuration
    conf_loader.load_from_config_file(config, config_filename)
  File "/Users/jharrington/code/ClusterRunner/app/util/conf/base_config_loader.py", line 107, in load_from_config_file
    self._load_section_from_config_file(config, config_filename, self.CONFIG_FILE_SECTION)
  File "/Users/jharrington/code/ClusterRunner/app/util/conf/base_config_loader.py", line 154, in _load_section_from_config_file
    self._cast_and_set(key, value, config)
  File "/Users/jharrington/code/ClusterRunner/app/util/conf/base_config_loader.py", line 164, in _cast_and_set
    config.set(key, int(value))
ValueError: invalid literal for int() with base 10: 'False'
```

The bug was introduced with [this change](https://github.com/box/ClusterRunner/commit/55fef394df0053a9bc5e3dfc910914699807ab56#diff-6e4b0b5265e2332751166695c401ae3aR159) that replaced `type(x) is y` checks with `isinstance(x, y)`. The problem here is that `bool` is actually a subclass of `int`, so adding the `isinstance` checks actually changed the behavior of the code.

**Comment by josephharrington** [comment]
Fixed in #149.
