### ISSUE TITLE
Flaky test in TestClusterSlave

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#178]
The test `test_executing_build_teardown_multiple_times_will_not_raise_exception` in test_cluster_slave.py is flaky. Here is the failure:

```
======================================================================
FAIL: test_executing_build_teardown_multiple_times_will_not_raise_exception() iteration_081 (test.unit.slave.test_cluster_slave.TestClusterSlave)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jharrington/.virtualenvs/clusterrunner/lib/python3.4/site-packages/genty/genty.py", line 282, in <lambda>
    test_method_for_dataset = lambda *my_self: method(*my_self)
  File "/Users/jharrington/code/ClusterRunner/test/unit/slave/test_cluster_slave.py", line 187, in test_executing_build_teardown_multiple_times_will_not_raise_exception
    project_type_mock.teardown_build.assert_called_once_with(timeout=None)
  File "/usr/local/Cellar/python3/3.4.2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/unittest/mock.py", line 781, in assert_called_once_with
    raise AssertionError(msg)
AssertionError: Expected 'teardown_build' to be called once. Called 0 times.
```

**Comment by josephharrington** [comment]
I don't remember seeing this recently. We can reopen if it comes back.
