### ISSUE TITLE
Tornado error on read

### ISSUE THREAD

**Issue by drobertduke** [box/ClusterRunner#228]
I had a build fail in the middle of execution because the slave couldn't post results back to the master.  Here are the master logs:

```
2015-07-13 12:09:04.315] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2012.pod.box.net:43001 for subjob. (Build 7, Subjob 33)
[2015-07-13 12:14:53.821] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2012.pod.box.net:43001 for subjob. (Build 7, Subjob 167)
[2015-07-13 12:21:31.880] 12073 WARNING MasterTornadoTh tornado.general error on read
Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/iostream.py", line 404, in _handle_read
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/iostream.py", line 460, in _read_to_buffer
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/iostream.py", line 696, in read_from_fd
TimeoutError: [Errno 110] Connection timed out
[2015-07-13 12:21:46.274] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2012.pod.box.net:43001 for subjob. (Build 7, Subjob 228)
[2015-07-13 12:21:46.277] 12073 WARNING MasterTornadoTh build           Writing payload for subjob 228 of build 7 FAILED.
[2015-07-13 12:21:46.278] 12073 ERROR   MasterTornadoTh build           Error while completing subjob; marking build as failed.
Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 2249, in next
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1083, in fromtarfile
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1019, in frombuf
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 224, in complete_subjob
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 260, in _handle_subjob_payload
  File "/home/jenkins/ClusterRunnerBuild/app/util/fs.py", line 86, in extract_tar
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1566, in open
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1620, in gzopen
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1596, in taropen
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1470, in __init__
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 2264, in next
tarfile.ReadError: empty file
[2015-07-13 12:21:46.279] 12073 ERROR   MasterTornadoTh build           Build 7 failed: Error occurred while completing subjob 228.
[2015-07-13 12:21:46.279] 12073 ERROR   MasterTornadoTh cluster_base_ha Exception occurred during request to /v1/build/7/subjob/228/result.
Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 2249, in next
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1083, in fromtarfile
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1019, in frombuf
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/web.py", line 1346, in _when_complete
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/web.py", line 1367, in _execute_method
  File "/home/jenkins/ClusterRunnerBuild/app/web_framework/cluster_master_application.py", line 126, in post
  File "/home/jenkins/ClusterRunnerBuild/app/master/cluster_master.py", line 275, in handle_result_reported_from_slave
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 224, in complete_subjob
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 260, in _handle_subjob_payload
  File "/home/jenkins/ClusterRunnerBuild/app/util/fs.py", line 86, in extract_tar
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1566, in open
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1620, in gzopen
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1596, in taropen
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1470, in __init__
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 2264, in next
tarfile.ReadError: empty file
[2015-07-13 12:21:46.281] 12073 ERROR   MasterTornadoTh tornado.access  500 POST /v1/build/7/subjob/228/result (10.5.248.194) 7.39ms
[2015-07-13 12:33:23.377] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2011.pod.box.net:43001 for subjob. (Build 7, Subjob 110)
[2015-07-13 12:35:07.316] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2011.pod.box.net:43001 for subjob. (Build 7, Subjob 112)
[2015-07-13 12:36:52.604] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2014.pod.box.net:43001 for subjob. (Build 7, Subjob 117)
[2015-07-13 12:38:06.341] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2013.pod.box.net:43001 for subjob. (Build 7, Subjob 109)
[2015-07-13 12:39:15.229] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2013.pod.box.net:43001 for subjob. (Build 7, Subjob 126)
[2015-07-13 12:49:06.533] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2012.pod.box.net:43001 for subjob. (Build 7, Subjob 120)
[2015-07-13 12:51:17.146] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2012.pod.box.net:43001 for subjob. (Build 7, Subjob 125)
[2015-07-13 12:52:45.903] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2012.pod.box.net:43001 for subjob. (Build 7, Subjob 100)
[2015-07-13 12:52:47.742] 12073 INFO    MasterTornadoTh cluster_master  Results received from pod4101-automation2012.pod.box.net:43001 for subjob. (Build 7, Subjob 102)
[2015-07-13 12:52:48.034] 12073 ERROR   MasterTornadoTh cluster_base_ha Exception occurred during request to /v1/build/7/subjob/102/result.
Traceback (most recent call last):
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 193, in execute_next_subjob_or_teardown_slave
  File "/usr/local/lib/python3.4/queue.py", line 164, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/web.py", line 1346, in _when_complete
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/web.py", line 1367, in _execute_method
  File "/home/jenkins/ClusterRunnerBuild/app/web_framework/cluster_master_application.py", line 126, in post
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 205, in execute_next_subjob_or_teardown_slave
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 208, in _free_slave_executor
  File "/home/jenkins/ClusterRunnerBuild/app/master/slave.py", line 128, in free_executor
Exception: Cannot free executor on slave pod4101-automation2012.pod.box.net:43001. All are free.
[2015-07-13 12:52:48.037] 12073 ERROR   MasterTornadoTh tornado.access  500 POST /v1/build/7/subjob/102/result (10.5.248.194) 296.27ms
[2015-07-13 12:52:48.435] 12073 ERROR   MasterTornadoTh cluster_base_ha Exception occurred during request to /v1/slave/1.
Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/web.py", line 1346, in _when_complete
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/web.py", line 1367, in _execute_method
  File "/home/jenkins/ClusterRunnerBuild/app/util/decorators.py", line 63, in function_with_auth
  File "/home/jenkins/ClusterRunnerBuild/app/web_framework/cluster_master_application.py", line 244, in put
  File "/home/jenkins/ClusterRunnerBuild/app/master/cluster_master.py", line 165, in handle_slave_state_update
  File "/home/jenkins/ClusterRunnerBuild/app/master/slave_allocator.py", line 67, in add_idle_slave
  File "/home/jenkins/ClusterRunnerBuild/app/master/slave.py", line 49, in mark_as_idle
Exception: ('Trying to mark slave idle while {} executors still in use.', -1)
[2015-07-13 12:52:48.436] 12073 ERROR   MasterTornadoTh tornado.access  500 PUT /v1/slave/1 (10.5.248.194) 1.65ms
[2015-07-13 12:52:48.445] 12073 INFO    MasterTornadoTh cluster_master  Slave on pod4101-automation2012.pod.box.net:43001 was disconnected. (id: 1)
```

And from the slave (2012)

```
[2015-07-13 12:52:47.497] 21437 NOTICE  Bld7-Sub102     git             Command exited with non-zero exit code.
Command: export ATOM_ID="96"; export BUILD_EXECUTOR_INDEX="0"; export PROJECT_DIR="/tmp/clusterrunner_build_symlinks/437a68ac-476c-4828-9f3e-3422d90e3368"; export EXECUTOR_INDEX="0"; export MACHINE_EXECUTOR_INDEX="0"; export ARTIFACT_DIR="/home/jenkins/.clusterrunner/artifacts/7/artifact_102_96"; export TESTPATH="/tmp/clusterrunner_build_symlinks/437a68ac-476c-4828-9f3e-3422d90e3368/test/php/integration/models/GDrive_Object_Test.php"; cd $PROJECT_DIR && for i in 1 2; do PHPUNIT_THREAD_INDEX=$EXECUTOR_INDEX $PROJECT_DIR/phpunit --log-junit $ARTIFACT_DIR/result.xml $TESTPATH && break; done && test -f $ARTIFACT_DIR/result.xml && xmllint --noout $ARTIFACT_DIR/result.xml
Exit code: -15
Console output:

[2015-07-13 12:52:48.038] 21437 INFO    Bld7-Sub102     cluster_slave   Build 7, Subjob 102 completed and sent results to master.
[2015-07-13 12:52:48.432] 21437 INFO    Bld7-Teardwn    cluster_slave   Notifying master that this slave is ready for new builds.
[2015-07-13 12:52:48.436] 21437 ERROR   Bld7-Teardwn    unhandled_excep Unhandled exception handler caught exception.
Traceback (most recent call last):
  File "/home/jenkins/ClusterRunnerBuild/app/util/safe_thread.py", line 18, in run
  File "/usr/local/lib/python3.4/threading.py", line 868, in run
  File "/home/jenkins/ClusterRunnerBuild/app/slave/cluster_slave.py", line 162, in _async_teardown_build
  File "/home/jenkins/ClusterRunnerBuild/app/slave/cluster_slave.py", line 194, in _send_master_idle_notification
  File "/home/jenkins/ClusterRunnerBuild/app/slave/cluster_slave.py", line 322, in _notify_master_of_state_change
  File "/home/jenkins/ClusterRunnerBuild/app/util/network.py", line 83, in put_with_digest
  File "/home/jenkins/ClusterRunnerBuild/app/util/decorators.py", line 38, in function_with_retries
  File "/home/jenkins/ClusterRunnerBuild/app/util/network.py", line 71, in put
  File "/home/jenkins/ClusterRunnerBuild/app/util/network.py", line 125, in _request
app.util.network._RequestFailedError: Request to http://pod4101-automation2011.pod.box.net:43000/v1/slave/1 failed with status_code 500 and response "{"error": "('Trying to mark slave idle while {} executors still in use.', -1)"}"
[2015-07-13 12:52:48.440] 21437 DEBUG   Bld7-Teardwn    unhandled_excep Executing teardown callback: <bound method ClusterSlave._disconnect_from_master of <app.slave.cluster_slave.ClusterSlave object at 0x7ff85f85d4a8>>
[2015-07-13 12:52:48.443] 21437 INFO    Bld7-Teardwn    cluster_slave   Notifying master that this slave is disconnecting.
[2015-07-13 12:52:48.446] 21437 DEBUG   Bld7-Teardwn    unhandled_excep Executing teardown callback: <bound method ClusterSlave._do_build_teardown_and_reset of <app.slave.cluster_slave.ClusterSlave object at 0x7ff85f85d4a8>>
[2015-07-13 12:52:48.446] 21437 DEBUG   Bld7-Teardwn    unhandled_excep Executing teardown callback: <function ServiceSubcommand._write_pid_file.<locals>.remove_pid_file at 0x7ff85ee29158>
[2015-07-13 12:52:48.447] 21437 DEBUG   Bld7-Teardwn    unhandled_excep Executing teardown callback: functools.partial(<bound method EPollIOLoop.add_callback of <tornado.platform.epoll.EPollIOLoop object at 0x7ff85f86f0f0>>, callback=<bound method EPollIOLoop.stop of <tornado.platform.epoll.EPollIOLoop object at 0x7ff85f86f0f0>>)
[2015-07-13 12:52:48.448] 21437 NOTICE  SlaveTornadoThr subcommand      Slave server was stopped.
```

**Comment by josephharrington** [comment]
I don't think this is related to Tornado specifically.

My interpretation of this just from looking at the logs is that for some reason an invalid tar file was generated on the slave for subjob 167.

This line:
```
tarfile.EmptyHeaderError: empty header
```
suggest the master got an invalid tar file from the slave on subjob 167. That exception looks like it causes a cascade of other exceptions that ends up leaving the master's bookkeeping on the number of executors in use for the slave in an incorrect state.

Later, when the final subjob result (subjob 102) from that slave is successfully reported, the master tries to decrement the executor count to -1 which raises an exception. (`('Trying to mark slave idle while {} executors still in use.', -1)`) This exception results in a 500 response to the slave which takes down the slave.

We should look earlier in the slave logs while it was working on subjob 167 to see if there is anything hinting at why it might have created an invalid tar file.

**Comment by josephharrington** [comment]
Probably invalid now that we've deprecated tar files in favor of zips.
