### ISSUE TITLE
ClusterMaster gets taken down on git fetch failure

### ISSUE THREAD

**Issue by tjlee0909** [box/ClusterRunner#247]
Logs from pod4101-automation1000.pod.box.net (Cluster Master service)
```
^[[0m^[[36m[2015-08-14 12:49:04.044] 30340 INFO    MasterTornadoTh event_log       Queued request for build 2106.
^[[0m^[[36m[2015-08-14 12:49:04.045] 30340 INFO    Bld2106-Prepara build_request_h Build 2106 is waiting for the project lock
^[[0m^[[36m[2015-08-14 12:49:04.046] 30340 INFO    Bld2106-Prepara build_request_h Build 2106 has acquired project lock
^[[0m^[[36m[2015-08-14 12:49:04.047] 30340 INFO    Bld2106-Prepara event_log       Build preparation loop is handling request for build 2106.
^[[0m^[[36m[2015-08-14 12:49:04.049] 30340 INFO    Bld2106-Prepara build_request_h Fetching project for build 2106.
^[[0m^[[32m[2015-08-14 12:49:04.049] 30340 DEBUG   Bld2106-Prepara git             Executing command in project: export GIT_ASKPASS="/home/jenkins/.clusterrunner/dist/bin/git_askpass.sh"; export GIT_SSH="/home/jenkins/.clusterrunner/dist/bin/git_ssh.sh"; export GIT_SSH_ARGS="-o BatchMode=yes -o StrictHostKeyChecking=no"; export PROJECT_DIR="/tmp/clusterrunner_build_symlinks/ee05cfb5-aafa-4066-a70e-18b719e97f2f"; git rev-parse
^[[0m^[[32m[2015-08-14 12:49:04.485] 30340 DEBUG   Bld2106-Prepara git             Command completed with exit code 0.
^[[0m^[[32m[2015-08-14 12:49:04.486] 30340 DEBUG   Bld2106-Prepara git             Executing command in project: export GIT_ASKPASS="/home/jenkins/.clusterrunner/dist/bin/git_askpass.sh"; export GIT_SSH="/home/jenkins/.clusterrunner/dist/bin/git_ssh.sh"; export GIT_SSH_ARGS="-o BatchMode=yes -o StrictHostKeyChecking=no"; export PROJECT_DIR="/tmp/clusterrunner_build_symlinks/ee05cfb5-aafa-4066-a70e-18b719e97f2f"; git fetch --update-head-ok origin v5-dev
^[[0m^[[33m[2015-08-14 12:49:45.208] 30340 NOTICE  Bld2106-Prepara git             Command exited with non-zero exit code.
Command: export GIT_ASKPASS="/home/jenkins/.clusterrunner/dist/bin/git_askpass.sh"; export GIT_SSH="/home/jenkins/.clusterrunner/dist/bin/git_ssh.sh"; export GIT_SSH_ARGS="-o BatchMode=yes -o StrictHostKeyChecking=no"; export PROJECT_DIR="/tmp/clusterrunner_build_symlinks/ee05cfb5-aafa-4066-a70e-18b719e97f2f"; git fetch --update-head-ok origin v5-dev
Exit code: -15
Stdout: 
Stderr: Killed by signal 15.^M

^[[0m^[[1m^[[31m[2015-08-14 12:49:45.208] 30340 ERROR   Bld2106-Prepara build           Build 2106 failed: Could not fetch specified branch "v5-dev" from remote "origin". Command: "git fetch --update-head-ok origin v5-dev"
Output: "
Killed by signal 15.^M
"
^[[0m^[[1m^[[31m[2015-08-14 12:49:45.404] 30340 ERROR   Bld2106-Prepara build_request_h Could not handle build request for build 2106.
Traceback (most recent call last):
  File "/home/jenkins/ClusterRunnerBuild/app/master/build_request_handler.py", line 103, in _prepare_build_async
  File "/home/jenkins/ClusterRunnerBuild/app/master/build_request_handler.py", line 130, in _prepare_build
  File "/home/jenkins/ClusterRunnerBuild/app/project_type/project_type.py", line 82, in fetch_project
  File "/home/jenkins/ClusterRunnerBuild/app/project_type/git.py", line 177, in _fetch_project
  File "/home/jenkins/ClusterRunnerBuild/app/project_type/git.py", line 229, in _execute_git_command_in_repo_and_raise_on_failure
  File "/home/jenkins/ClusterRunnerBuild/app/project_type/project_type.py", line 98, in _execute_and_raise_on_failure
RuntimeError: Could not fetch specified branch "v5-dev" from remote "origin". Command: "git fetch --update-head-ok origin v5-dev"
Output: "
Killed by signal 15.^M
"
```

**Comment by josephharrington** [comment]
I don't think this type of failure currently takes down the master, and looking at commit 26c64b5 (around the time this issue was filed) I'm not sure it ever did. The exception in the stack trace should be caught by the `except Exception` block in `build_request_handler.py` which merely fails the build.

If there were further exceptions that took down the master then they are not captured here.
