### ISSUE TITLE
Registration timed out after 5 sec

### ISSUE THREAD

**Issue by sagannotcarl** [box/ClusterRunner#271]
I am working my way through the setup instructions with the demo project and I've gotten really stuck on the "Deploy and test the ClusterRunner service" section. I'm trying to set up a single replica server to start with.

This is what I'm seeing:
```
$ clusterrunner deploy --slaves 128.199.80.54
Compressing binaries...
Compressed tar file /home/colinsagan/.clusterrunner/dist/clusterrunner.tgz already exists, skipping compression.
Deploying binaries and confs on master and slaves...
Stopping and starting all clusterrunner services...
Validating successful deployment...
Slave registration timed out after 5 sec, with slaves 128.199.80.54 missing.
```

I'm probably missing something in the previous steps but I can't figure out what it is. Any suggestions for how I can debug my setup further?

Thanks!

**Comment by sagannotcarl** [comment]
I know it's not in the installation instructions but in an attempt to debug I ssh'ed directly to the replica server and seeing if anything was showing up.

I tried running ```clusterrunner slave``` there and I'm getting the following messages and errors. 

Obviously lots of http connection errors, is there some configuration around ports or something I'm missing? Both my primary and my replica servers are on Digital Ocean Ubuntu 14.04 x64.

Also those paths starting with ```home/jenkins``` look out of place to me. I'm not sure where that's coming from.

Here's the messages in case it's helpful:
```
$ clusterrunner slave
[2015-11-08 05:35:56.218] 7689 DEBUG   SlaveTornadoThr log
**************************************************
 ClusterRunner
  * Version: 0.5.409
  * PID:     7689
**************************************************

[2015-11-08 05:35:56.234] 7689 WARNING SlaveTornadoThr decorators      Call to Network.post raised ConnectionError("HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)"). Retrying in 0.1 seconds.
[2015-11-08 05:35:56.337] 7689 WARNING SlaveTornadoThr decorators      Call to Network.post raised ConnectionError("HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)"). Retrying in 0.2 seconds.
[2015-11-08 05:35:56.542] 7689 WARNING SlaveTornadoThr decorators      Call to Network.post raised ConnectionError("HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)"). Retrying in 0.4 seconds.
[2015-11-08 05:35:56.948] 7689 WARNING SlaveTornadoThr decorators      Call to Network.post raised ConnectionError("HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)"). Retrying in 0.8 seconds.
[2015-11-08 05:35:57.755] 7689 WARNING SlaveTornadoThr decorators      Call to Network.post raised ConnectionError("HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)"). Retrying in 1.6 seconds.
[2015-11-08 05:35:59.360] 7689 WARNING SlaveTornadoThr decorators      Call to Network.post raised ConnectionError("HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)"). Retrying in 3.2 seconds.
[2015-11-08 05:36:02.570] 7689 WARNING SlaveTornadoThr decorators      Call to Network.post raised ConnectionError("HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)"). Retrying in 6.4 seconds.
[2015-11-08 05:36:08.979] 7689 WARNING SlaveTornadoThr decorators      Call to Network.post raised ConnectionError("HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)"). Retrying in 12.8 seconds.
[2015-11-08 05:36:21.797] 7689 ERROR   SlaveTornadoThr tornado.applica Exception in callback functools.partial(<function wrap.<locals>.wrapped at 0x7f87dd442268>)
Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 493, in urlopen
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 291, in _make_request
  File "/usr/local/lib/python3.4/http/client.py", line 1088, in request
  File "/usr/local/lib/python3.4/http/client.py", line 1126, in _send_request
  File "/usr/local/lib/python3.4/http/client.py", line 1084, in endheaders
  File "/usr/local/lib/python3.4/http/client.py", line 922, in _send_output
  File "/usr/local/lib/python3.4/http/client.py", line 857, in send
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 106, in connect
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 90, in _new_conn
  File "/usr/local/lib/python3.4/socket.py", line 512, in create_connection
  File "/usr/local/lib/python3.4/socket.py", line 503, in create_connection
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/adapters.py", line 327, in send
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 543, in urlopen
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/ioloop.py", line 477, in _run_callback
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/stack_context.py", line 331, in wrapped
  File "<string>", line 3, in raise_exc_info
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/stack_context.py", line 302, in wrapped
  File "/home/jenkins/ClusterRunnerBuild/app/slave/cluster_slave.py", line 227, in connect_to_master
  File "/home/jenkins/ClusterRunnerBuild/app/util/decorators.py", line 38, in function_with_retries
  File "/home/jenkins/ClusterRunnerBuild/app/util/network.py", line 48, in post
  File "/home/jenkins/ClusterRunnerBuild/app/util/network.py", line 122, in _request
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/sessions.py", line 456, in request
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/sessions.py", line 559, in send
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/adapters.py", line 375, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=43000): Max retries exceeded with url: /v1/slave (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)
```

**Comment by josephharrington** [comment]
Hey @sagannotcarl, my first guess is that your slave host is not able to reach your master host via http for some reason.

One thing you can try to confirm this is starting up the master service on one host, and then just try doing a `curl` call from the slave host to the master service's api:
```bash
curl http://$MASTER_HOST:43000/v1/version
```

You should see a response similar to:
```
{"version": "0.5.417", "child_routes": {}}
```

(43000 is the default port, but it's configurable.) If that fails, then it is probably a firewall/port configuration issue. I'm not sure the http requirement is explicitly stated in the docs but we should definitely add it if that actually ends up being the solution to your issue.

Also, if you are using the prebuilt package downloaded from the clusterrunner.com site, then the "/home/jenkins/..." paths you are seeing are probably just an artifact of our build process.

Thanks for reaching out! Let us know how it goes -- we're happy to help get you up and running. :)

**Comment by sagannotcarl** [comment]
Great, thanks for the info. I was able to get them communicating by manually starting up the master service and the slave service and by editing the configuration file on each to set the correct ip. I was able to get the tests properly running one time but then I tried running the deploy command as in the setup instructions and I wasn't able to get it working again. Maybe I'll try again from scratch to see if I just missed something in the setup.

As for the "/home/jenkins/..." paths, should I be doing something other than using the prebuilt package? Could those path issues be causing problems?

**Comment by tjlee0909** [comment]
Re: the /home/jenkins paths

That's due to how we packaged ClusterRunner (we ran the CXFreeze build process on a jenkins slave, using the jenkins user). I understand why that path might look concerning, but it shouldn't be an issue.

Re: the crappy deploy subcommand

We have had some serious issues with the deploy subcommand in ClusterRunner, and have actually replaced it with an init.d script that performs a series of bash commands to manage the invocation of the processes. Unfortunately, it being an init.d script, it only works on linux, and so we have not released it to the general public.

You're approach of manually starting the up master and slave subcommands is pretty much what deployment looks like (except automated of course).

**Comment by tjlee0909** [comment]
@sagannotcarl - I uploaded both the init.d script, as well as the sysconfig file in this Pull Request:

https://github.com/box/ClusterRunner/pull/272

**Comment by josephharrington** [comment]
A few other ideas I had to help debug:

1. I noticed you are using IPs to refer to your hosts. Internally, `clusterrunner deploy` is actually using [`socket.gethostname()`](https://docs.python.org/3.4/library/socket.html#socket.gethostname) to determine the master's hostname, and then launches the slave service using that result. The exact command that `clusterrunner deploy` ends up executing to launch the slave from the master is something like:
  ```bash
ssh -o StrictHostKeyChecking=no jharrington@slave.dev.box.net 'nohup /home/jharrington/.clusterrunner/dist/clusterrunner slave --master-url master.dev.box.net:43000 --port 43001 --num-executors 1 &'
  ```

  The difference here is that usually `socket.gethostname()` does not return an IP address, it returns an actual hostname (e.g., "master.dev.box.net"). So it may be that your slave host is able to reach the master via its IP (as you saw when you launched the slave manually) but maybe the slave is not able to reach the master via its hostname.

  If that's the case, I believe you may be able to work around that by specifying the master's IP in your `deploy` command like:
  ```
  clusterrunner deploy --master 128.199.80.1 --slaves 128.199.80.2
  ```

2. You can also specify a `-v` to get more verbose output (`clusterrunner deploy -v ...`). Maybe there will be clues in there about where things are breaking down.

3. After running `deploy` and seeing the failure, you can check `~/.clusterrunner/log/clusterrunner_master.log` on the master host and `~/.clusterrunner/log/clusterrunner_slave.log` on the slave host for the full application logs. This will contain output similar to what you posted in your second comment above, and may also contain some clues about which side is hitting errors.

Hopefully this is helpful! And thanks again. This feedback definitely helps us determine where to focus on improving the setup process and documentation. :smile:

**Comment by josephharrington** [comment]
And to elaborate on TJ's comment above ("serious issues with the deploy subcommand") -- I think most of the issues we ran into were related to scale. By default, `deploy` will fail if *any* of the slave deployments fail and since we're running >100 slaves it became pretty likely that one would fail due to any number of random environmental reasons. `deploy` should definitely be more stable on a small scale, although as you're seeing, the error output can be pretty obscure.

Because of the scale issues with the current `clusterrunner deploy` implementation, and because of some new internal high availability (HA) requirements, we ended up rewriting the `deploy` functionality as an init.d script to get better integration into other existing tools and processes. The downside is that it's less self-contained and less cross-platform and we haven't had a chance yet to integrate the two, although there's nothing technical preventing that.

**Comment by sagannotcarl** [comment]
@josephharrington and @tjlee0909: Thanks for all the tips. I'll give all of this a try and report back!

**Comment by josephharrington** [comment]
Hey @sagannotcarl, any luck?

**Comment by sagannotcarl** [comment]
@josephharrington, I haven't had a chance to try doing the deployment setup again. But I've been using clusterrunner locally and it's been great. Having the link to the init.d script was very helpful. I can close this issue for now and if I'm still having trouble using the init.d script I'll open another issue.

Thanks!
