### ISSUE TITLE
Failure to start a subjob on a slave can take down the master

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#337]
The code to send a subjob to a slave uses a SafeThread, which is intended to only be used for application critical threads. This means if the request fails (for example due to a connection error or network timeout) then the master service could go down.

This is relatively unlikely since a subjob is only sent when the build first starts (in which case we've very recently confirmed that the slave is responsive), or when the slave itself sends results for a previous subjob (in which case it's unlikely that the slave goes down in the small window between sending a result and receiving new work).

**Comment by josephharrington** [comment]
Aaaand, we got hit by this today:
```
Traceback (most recent call last):
  File "/home/jenkins/ClusterRunnerBuild/app/util/safe_thread.py", line 18, in run
    super().run()
  File "/usr/local/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jenkins/ClusterRunnerBuild/app/master/slave.py", line 128, in _async_start_subjob
    response = self._network.post_with_digest(execution_url, post_data, Secret.get(), error_on_failure=True)
  File "/home/jenkins/ClusterRunnerBuild/app/util/network.py", line 73, in post_with_digest
    encoded_body = self.encode_body(request_params)
  File "/home/jenkins/ClusterRunnerBuild/app/util/decorators.py", line 38, in function_with_retries
    return function(*args, **kwargs)
  File "/home/jenkins/ClusterRunnerBuild/app/util/network.py", line 61, in post
    """
  File "/home/jenkins/ClusterRunnerBuild/app/util/network.py", line 148, in _request
    data_to_send = {ENCODED_BODY: self.encode_body(data_to_send)}
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/requests/adapters.py", line 384, in send
    raise Timeout(e, request=request)
requests.exceptions.Timeout: HTTPConnectionPool(host='ip-10-228-99-153.pod.box.net', port=43001): Read timed out. (read timeout=30)
```
It did indeed bring down the master service. :woman_facepalming:
