### ISSUE TITLE
FileNotFoundError when creating zip archive

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#339]
This is a new bug (introduced with the recent zip archive change) ~that triggers #323, bringing down the master service~. (Edit: #343 was merged to prevent this from taking down the master.)
```
[2017-05-15 02:57:53.006] 9852 INFO    MasterTornadoTh build           All results received for build 4!
[2017-05-15 02:57:54.673] 9852 DEBUG   PostBuild4      build_artifact  Overwrote existing timing file in /home/jenkins/.clusterrunner/timings/master/gitosis@devscmro.dev.box.net/appconf/PHPUnit.timing.json
[2017-05-15 02:58:04.139] 9852 ERROR   PostBuild4      unhandled_excep Unhandled exception handler caught exception.
Traceback (most recent call last):
  File "/home/jenkins/ClusterRunnerBuild/app/util/safe_thread.py", line 18, in run
    super().run()
  File "/usr/local/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 459, in _perform_async_postbuild_tasks
    self._create_build_artifact()
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 469, in _create_build_artifact
    BuildArtifact.ARTIFACT_ZIPFILE_NAME)
  File "/home/jenkins/ClusterRunnerBuild/app/util/fs.py", line 134, in zip_directory
    tmp_path = shutil.make_archive(tempfile.mktemp(), 'zip', target_dir)
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/shutil.py", line 785, in make_archive
    filename = func(base_name, base_dir, **kwargs)
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/shutil.py", line 690, in _make_zipfile
    zf.write(path, path)
  File "/usr/local/lib/python3.4/zipfile.py", line 1366, in write
    with open(filename, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'artifact_531_11/result.xml'
```

**Comment by josephharrington** [comment]
This is pretty weird because this is coming from inside the stdlib, and the line write before `zf.write()` in shutil checks for file existence:
```python
for dirpath, dirnames, filenames in os.walk(base_dir):
    for name in filenames:
        path = os.path.normpath(os.path.join(dirpath, name))
        if os.path.isfile(path):
            zf.write(path, path)  # <--- This line calls zipfile which raises FileNotFound
```

**Comment by josephharrington** [comment]
After merging a change to create the tar.gz archive first and the zip archive second (ignoring errors on the zip creation) we still see the above FileNotFoundError in the logs. Coincidentally (or not?) it occurred again on a result.xml file. The file it complained about **does** exist in the tar.gz archive and looks completely normal.

I'm not sure what else to try except changing the zip archive creation logic to stop using `shutil.make_archive` and use `zipfile` directly.

#stumped 😑

**Comment by josephharrington** [comment]
I did find one surprising thing.

I downloaded the artifacts.tar.gz and the artifacts.zip for a build where archive creation succeeded and found that the zip archive is simply missing about 10% of the files:
```
🍕 🍕 🍕  ~/Downloads ☰  find artifacts-tar/ | wc -l
   32413
🍕 🍕 🍕  ~/Downloads ☰  find artifacts-zip/ | wc -l
   30607
```
By diffing the file lists it looks like the zip archive just skipped over entire directories:
```
🍕 🍕 🍕  ~/Downloads ☰  diff tarlist.txt ziplist.txt
2,7d1
< ./artifact_0_0
< ./artifact_0_0/clusterrunner_command
< ./artifact_0_0/clusterrunner_console_output
< ./artifact_0_0/clusterrunner_exit_code
< ./artifact_0_0/clusterrunner_time
< ./artifact_0_0/result.xml
80,85d73
< ./artifact_105_0
< ./artifact_105_0/clusterrunner_command
< ./artifact_105_0/clusterrunner_console_output
< ./artifact_105_0/clusterrunner_exit_code
< ./artifact_105_0/clusterrunner_time
< ./artifact_105_0/result.xml
326,331d313
< ./artifact_120_0
< ./artifact_120_0/clusterrunner_command
< ./artifact_120_0/clusterrunner_console_output
< ./artifact_120_0/clusterrunner_exit_code
< ./artifact_120_0/clusterrunner_time
< ./artifact_120_0/result.xml
338,343d319
< ./artifact_121_0
< ./artifact_121_0/clusterrunner_command
< ./artifact_121_0/clusterrunner_console_output
< ./artifact_121_0/clusterrunner_exit_code
< ./artifact_121_0/clusterrunner_time
< ./artifact_121_0/result.xml
824,829d799
... (lots and lots of the same)
```

So yeah, that's weird.

**Comment by cmcginty** [comment]
@josephharrington Do we know if #389 ended up fixing this issue?

**Comment by josephharrington** [comment]
@cmcginty I think so -- I remember being pretty confident in that fix. Looking at #343 you should be able to verify this is no longer occurring by grepping the master logs for `"Zipping of artifacts failed"`.

**Comment by cmcginty** [comment]
Not found, closing.
