### ISSUE TITLE
All builds fail when master process has too many open files

### ISSUE THREAD

**Issue by josephharrington** [box/ClusterRunner#69]
The symptom of the issue is that all builds start failing and will continue to fail until the master service is restarted. 

The stack trace we see in the master log for the failed builds is:
```
[2015-01-12 14:00:51.914] ERROR   RequestHandlerL build           Build 564 failed: filedescriptor out of range in select()
[2015-01-12 14:00:51.917] ERROR   RequestHandlerL cluster_master  Could not handle build request for build 564
Traceback (most recent call last):
  File "/home/jenkins/ClusterRunnerBuild/app/master/cluster_master.py", line 321, in _build_preparation_loop
    self._request_handler.handle_request(build)
  File "/home/jenkins/ClusterRunnerBuild/app/master/serial_request_handler.py", line 56, in handle_request
    project_type.fetch_project()
  File "/home/jenkins/ClusterRunnerBuild/app/project_type/project_type.py", line 88, in fetch_project
    self._fetch_project()
  File "/home/jenkins/ClusterRunnerBuild/app/project_type/git.py", line 150, in _fetch_project
    self._execute_git_remote_command(fetch_command, self._repo_directory)
  File "/home/jenkins/ClusterRunnerBuild/app/project_type/git.py", line 181, in _execute_git_remote_command
    ['^User.*:', '^Pass.*:', '.*Are you sure you want to continue connecting.*'], timeout=timeout)
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/pexpect/__init__.py", line 1451, in expect
    timeout, searchwindowsize)
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/pexpect/__init__.py", line 1466, in expect_list
    timeout, searchwindowsize)
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/pexpect/__init__.py", line 1535, in expect_loop
    c = self.read_nonblocking(self.maxread, timeout)
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/pexpect/__init__.py", line 958, in read_nonblocking
    r, w, e = self.__select([self.child_fd], [], [], timeout)
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/pexpect/__init__.py", line 1717, in __select
    return select.select(iwtd, owtd, ewtd, timeout)
ValueError: filedescriptor out of range in select()
```

**Comment by josephharrington** [comment]
The stack trace above (`ValueError: filedescriptor out of range in select()`) is related to this pexpect issue: https://github.com/pexpect/pexpect/issues/47

Essentially, pexpect stops working once the number of open file handles for the Python process surpasses 1024. This seems like a high number, but running `ulimit -n` in our environment indicates a process should be able to have ten times that many handles. 

The main culprit of the large number of file handles is actually the keep-alive connections between the master and slave services. From investigation, it looks like the master can have up to 20 open files (tcp connections) per slave -- ten incoming and ten outgoing connections. This alone will allow the number of file handles to surpass 1024 with about 50 slaves.

We should make two changes to remedy this: figure out how to raise or work around pexpect's 1024 limit, and we should also reduce the number of connections held open between the master and slave.
