### ISSUE TITLE
If a slave fails to post results back to master, there's no retry or error logic to handle it, slave hangs indefinitely

### ISSUE THREAD

**Issue by michaelb990** [box/ClusterRunner#98]
I'm running into a situation while running tests where we will see sporadic failures after a slave finished executing a subjob and calls Network.post to send the results back to master. If the POST call fails, the slave does not check the return code and will wait for new jobs to be assigned indefinitely. This causes the build to hang because the master hasn't received results back for all the subjobs. I'm trying to add some additional logging to some of the slave classes and/or retry logic on the post call, but I'm not too familiar with the code. I've attached some of the logs from the slave below, let me know if you see something.

```
[2015-02-19 11:06:18.634] DEBUG   Bld63-Sub15     project_type    Command completed with exit code 0.
[2015-02-19 11:06:25.852] WARNING Bld63-Sub15     decorators      Call to Network.post raised ConnectionError("HTTPConnectionPool(host='ip-10-110-90-25.us-west-2.compute.internal', port=43000): Max retries exceeded with url: /v1/build/63/subjob/15/result (Caused by <class 'ConnectionResetError'>: [Errno 104] Connection reset by peer)"). Retrying in 0.1 seconds.
[2015-02-19 11:06:25.970] INFO    Bld63-Sub15     cluster_slave   Build 63, Subjob 15 completed and sent results to master.
```

**Comment by josephharrington** [comment]
Hey Michael, thanks for pointing this out -- this definitely looks like a bug. We even have a todo in the code there to check the POST request return code. :sweat_smile:

We definitely need to work on network robustness -- potentially adding retries with some exponential backoff. We'll see if we can get something out this week.

Just curious though - do you think the reason the call is failing is just due to random network flakiness in your infrastructure or do you suspect something on the ClusterRunner side?

**Comment by michaelb990** [comment]
Yeah, I saw that in my investigation, as well 😄. I'm running a cluster with about 10 slaves right now, and everything is in AWS. It could definitely be all network flakiness, or it could have something to do (in part) with ClusterRunner. A couple of my guesses were that it was related to longer running jobs and/or large artifacts being returned, as these subjobs that are failing are on the long side and seem to have some failures. However, it's definitely not a hard and fast rule, as I also see longer jobs that are returning bigger payloads just fine. I'll let you know if I find out anything else!



—

**Comment by michaelb990** [comment]
Found this buried in the logs of the master instance. Looks like the server is failing to save the artifacts. This might be something strange about one of my jobs, as it seems to be pretty consistently happening in the same job.
```
[2015-02-26 12:15:31.493] INFO    MasterTornadoTh cluster_master  Results received from ip-10-110-90-54.us-west-2.compute.internal:43001 for subjob. (Build 32, Subjob 1)
[2015-02-26 12:15:31.493] WARNING MasterTornadoTh build           Writing payload for subjob 1 of build 32 FAILED.
[2015-02-26 12:15:31.494] ERROR   MasterTornadoTh cluster_base_ha Exception occurred during request to /v1/build/32/subjob/1/result.
Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 2248, in next
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1083, in fromtarfile
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1019, in frombuf
tarfile.EmptyHeaderError: empty header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/web.py", line 1346, in _when_complete
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/site-packages/tornado/web.py", line 1367, in _execute_method
  File "/home/jenkins/ClusterRunnerBuild/app/web_framework/cluster_master_application.py", line 123, in post
  File "/home/jenkins/ClusterRunnerBuild/app/master/cluster_master.py", line 237, in handle_result_reported_from_slave
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 205, in complete_subjob
  File "/home/jenkins/ClusterRunnerBuild/app/master/build.py", line 220, in _handle_subjob_payload
  File "/home/jenkins/ClusterRunnerBuild/app/util/fs.py", line 84, in extract_tar
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1565, in open
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1619, in gzopen
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1595, in taropen
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 1469, in __init__
  File "/home/jenkins/.virtualenvs/clusterrunner/lib/python3.4/tarfile.py", line 2263, in next
tarfile.ReadError: empty file
[2015-02-26 12:15:31.494] ERROR   MasterTornadoTh tornado.access  500 POST /v1/build/32/subjob/1/result (10.110.90.54) 2.18ms
```
I'll let you know if I can figure out what specifically is special about this job.

**Comment by tjlee0909** [comment]
Hey Michael, could you paste the job definition from your clusterrunner.yaml file for the job that is responsible for this failure?

**Comment by michaelb990** [comment]
I can, but I don't know how helpful it will be. Pretty much what I'm doing is running cucumber tests in a virtual display (xvfb-run) and archiving the JUnit xml test reports, screenshots and the generic ClusterRunner files. I'm going to try some combinations and see if I can get a repro with any of our other jobs. All the other jobs do pretty much the same thing (using the generic execute_test.sh script). Here it is:
```yaml
GovStatRC_Firefox:
  commands:
    - cd automated_testing_projects/govstat
    - export BROWSER=firefox && export ENVIRONMENT=govstat_rc
    - xvfb-run ../../tools_and_scripts/execute_test.sh $FEATURE_FILE $ARTIFACT_DIR
  atomizers:
    - FEATURE_FILE: cd automated_testing_projects/govstat/ && ls features/regression_suite/*.feature
```
